name: CI Test Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 360main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build base
        uses: docker/build-push-action@v2
        with:
          context: ./base
          load: true
          tags: |
            ${JITSI_REPO}/base:latest
          build-args: |
            JITSI_RELEASE=unstable

      - name: Build base-java
        uses: docker/build-push-action@v2
        with:
          context: ./base-java
          load: true
          tags: |
            ${JITSI_REPO}/base-java:latest

      - name: Build jibri
        uses: docker/build-push-action@v2
        with:
          context: ./jibri
          load: true
          tags: |
            ${JITSI_REPO}/jibri:latest

      - name: Build jicofo
        uses: docker/build-push-action@v2
        with:
          context: ./jicofo
          load: true
          tags: |
            ${JITSI_REPO}/jicofo:latest

      - name: Build jigasi
        uses: docker/build-push-action@v2
        with:
          context: ./jigasi
          load: true
          tags: |
            ${JITSI_REPO}/jigasi:latest

      - name: Build jvb
        uses: docker/build-push-action@v2
        with:
          context: ./jvb
          load: true
          tags: |
            ${JITSI_REPO}/jvb:latest

      - name: Build prosody
        uses: docker/build-push-action@v2
        with:
          context: ./prosody
          load: true
          tags: |
            ${JITSI_REPO}/prosody:latest

      - name: Build web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          load: true
          tags: |
            ${JITSI_REPO}/web:latest
